config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  resources :stores  
  resources :users
  root to: 'stores#index'
  get 'stores_list', to: 'stores#stores_list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    can :read ,:store

    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
	belongs_to :store
	validates :name,presence: true
	validates :price,presence: true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :foods,inverse_of: :store,dependent: :destroy
	accepts_nested_attributes_for :foods, reject_if: :all_blank, allow_destroy: true
 	has_one_attached :logo

	geocoded_by :address   # can also be an IP address
	reverse_geocoded_by :latitude, :longitude

	after_validation :geocode          # auto-fetch coordinates
	
	validates :address,presence: true
	validates :name,presence: true

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :price)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    @hash = Gmaps4rails.build_markers(@stores) do |store, marker|
            marker.lat store.latitude
            marker.lng store.longitude
            marker.infowindow store.name

    end
  end

  def stores_list
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Loja criada com sucesso.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Loja Atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Loja deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address,:logo,:longitude,:latitude,foods_attributes: [:id,:name,:price,:_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h2>Editando essa Comida</h2>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.price %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodXD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <%= favicon_link_tag 'eat-circle.png', :rel => 'shortcut icon' %>
  </head>

  <body>
    <%- if current_user.present?%>

    <ul id="slide-out" class="side-nav fixed z-depth-4">

        <li><a class="subheader"><%=current_user.email%></a></li>
        
        <li>
          <%= link_to('Log out'.html_safe,  destroy_user_session_path , method: 'delete',class: 'waves-effect waves-light btn')%>
        </li>

        <li>
          <form class="sidebar-form">
            <div class="input-group">
              <input id="accounts" type="text" name="username" class="form-control" placeholder="Universal Search" autocomplete="off" />
            </div>
          </form>
        </li>

        <li>
         <%= link_to root_path, title: "dashboard", class: "active" do %>
          Dashboard
          <i class="material-icons pink-item">dashboard</i>
        <% end %>
        </li>

        <li><div class="divider"></div></li>

        <li><a class="subheader">Opções</a></li>

        <li>
          <%= link_to (stores_list_path), title: "Lojas" do %>
            Lojas
            <i class="material-icons pink-item">store</i>
          <% end %>
        </li>

        <li>
          <%= link_to (new_store_path), title: "Adicionar Loja" do %>
            Adicionar Loja
            <i class="material-icons pink-item">add_shopping_cart</i>
          <% end %>
        </li>

        <%- if current_user.has_role? :admin%>
          <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
              <li>
                <a class="collapsible-header">Gerenciar Usuários<i class="material-icons pink-item">person</i></a>
                <div class="collapsible-body">
                  <ul>
                    <li>
                      <%= link_to (users_path), title: "Usuários" do %>
                      Ver Usuários
                      <% end %>
                    </li>
                    
                  </ul>
                </div>
              </li>
            </ul>
          </li>
        <% end %>
        
      </ul>

  <% end %>
  
      <main>
        <section class="content">
           <div class="page-announce valign-wrapper"><a href="#" data-activates="slide-out" class="button-collapse valign hide-on-large-only"><i class="material-icons">menu</i></a><h1 class="page-announce-text valign">FoodXD</h1></div>
          <div class="container">
          <div class="row">
            <%= yield %>
          </div>
          </div>
        </section>
      </main>

  </body>

</html>

<script>
    // Hide sideNav
    $('.button-collapse').sideNav({
    menuWidth: 300, // Default is 300
    edge: 'left', // Choose the horizontal origin
    closeOnClick: false, // Closes side-nav on <a> clicks, useful for Angular/Meteor
      draggable: true // Choose whether you can drag to open on touch screens
      });
      $(document).ready(function(){
      $('.tooltipped').tooltip({delay: 50});
      });
      $('select').material_select();
      $('.collapsible').collapsible();
</script>

app/views/stores/_food_fields.html.erb
<div class="nested-fields">

    <div class="input-field col s6">
	    <%= f.input :name %>
	</div>

    <div class="input-field col s6">
	    <%= f.input :price %>
	    	
	</div>

	<%= link_to_remove_association "remover Comida", f ,class: 'btn btn-small'%>
<br>
<br>
</div>

app/views/stores/_form.html.erb
<div class="container">
  <div class="row">
    <%= simple_form_for @store,class: 'col s12' do |f| %>
      <%= f.error_notification errors:true%>

  <div class="row">
    <div class="input-field col s6">
      <%= f.input :name %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s6">
      <%= f.input :address %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s6">
      <%= f.input :longitude %>
    </div>
  </div>

    <div class="row">
    <div class="input-field col s6">
      <%= f.input :latitude %>
    </div>
  </div>

   <div class="file-field input-field">
      <div class="btn">
        <span>Logo</span>
        <%= f.input :logo,label: false %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

  <h4>Comidas</h4>
  <div id="foods">
    <%= f.simple_fields_for :foods do |food| %>
      <%= render 'food_fields', f: food %>
    <% end %>
   </div>

   <div class="links">
     <%= link_to_add_association '+Comida', f, :foods ,class: "btn waves-effect waves-light blue right white-text"%>
     <br><br>
   </div>

  <div class="row center-align">
      <%= f.button :submit ,class: 'btn btn-primary grey'%>
  </div>
<% end %>
  </div>
</div>

app/views/stores/edit.html.erb
<h4 class="flow-text">Editando <%=@store.name%></h4>


<%= render 'form', store: @store %>


<div class="center-align">
	
	<%= link_to 'Voltar', stores_path ,class: 'waves-effect waves-light btn'%>
</div>

app/views/stores/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyC4Av88lDd9X-Mm8YINVUcNMZ3AnhE435U"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<p id="notice"><%= notice %></p>


  <div style='width: 800px;'>
    <div class="center-align" id="geolocation" style='width: 1000px; height: 600px;'></div>
  </div>


<script type="text/javascript">
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
});
 

function displayOnMap(position){
  var hash_watashi = new Array();
  var hash_stores = <%=raw @hash.to_json %> // hash da posicao das stores
  var size_of_stores = hash_stores.length;

  hash_watashi[size_of_stores] = { // hash da posicao do usuario
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    picture: {
        url: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
        width:  36,
        height: 36
      },
    infowindow: "Eu!"
  };


  hash_complete = $.extend(hash_watashi, hash_stores); // hash fundido com os dois hashers

  var markers = handler.addMarkers(
      hash_complete
  );

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();

};
  
</script>

app/views/stores/new.html.erb
<div class="row">

	<h4 align="center">Nova loja</h4>

	<%= render 'form', store: @store %>

</div>
<div class="center-align">
	
	<%= link_to 'Voltar', stores_path ,class: 'waves-effect waves-light btn'%>
</div>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.latitude if @store.latitude.present?%>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.longitude if @store.longitude.present? %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>

app/views/stores/stores_list.html.erb
 <h3 class="center-align">Lojas Cadastradas</h3>
    <div class="custom-responsive">
      <table class="striped hover centered">
        <thead>
          <tr>
            <th>Logo</th>
            <th>Nome</th>
            <th>Endereço</th>
            <th colspan="3">Ações</th>

          </tr>
        </thead>

        <tbody>
          <% @stores.each do |store| %>

          <tr>
            <td>
              <div class="card horizontal">

                <div class="card-image">
                 <% if store.logo.attached? %>
                    <%=image_tag store.logo%>
                  <% end %>
                </div>
              </div>
            </td>
            <td><p><%= store.name %></p></td>
            <td><p><%= store.address %></p></td>
            <td>
              <%= link_to store  do %>
              <i class="material-icons left">remove_red_eye</i>
              <% end %>
            </td>
            <td>
                          
              <%= link_to edit_store_path(store) do%>
                  <i class="material-icons left">edit</i>
              <% end %>
            </td>
              <td>
                        
                <%= link_to store, method: :delete, data: { confirm: 'Você tem certeza?'}  do%>
                    <i class="material-icons left">clear</i>
                <% end %>
              </td>
                          
            </td>
          </tr>
                  
          <% end %>
        </tbody>
      </table>
    </div>

app/views/users/index.html.erb
  <h3 class="center-align">Usuários Cadastrados</h3>
    <div class="custom-responsive">
      <table class="striped hover centered">
        <thead>
          <tr>
            <th>email</th>
            <th colspan="3">Ações</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>

          <tr>
            <td><p><%= user.email %></p></td>
            <td>
              <%= link_to user  do %>
              <i class="material-icons left">remove_red_eye</i>
              <% end %>
            </td>
            <td>
                          
              <%= link_to edit_user_path(user) do%>
                  <i class="material-icons left">edit</i>
              <% end %>
            </td>
              <td>
                        
                <%= link_to user, method: :delete, data: { confirm: 'Você tem certeza?'}  do%>
                    <i class="material-icons left">clear</i>
                <% end %>
              </td>
                          
            </td>
          </tr>
                  
          <% end %>
        </tbody>
      </table>
    </div>